### ISSUE TITLE
install TCexam fatal error 89

### ISSUE THREAD

**Issue by yenz79** [tecnickcom/tcexam#439]
This is the [installation](http://localhost/tcexam/install/index.htm) script of [TCExam](http://www.tcexam.org/) by [Tecnick.com LTD](http://www.tecnick.com/)

DO NOT USE THIS SCRIPT FOR UPGRADING AN EXISTING INSTALLATION, INSTEAD READ [UPGRADE.TXT](http://localhost/tcexam/UPGRADE.TXT)

Please wait, this installation may take a while...

start TCExam installation............[OK]
start database installation.........[OK]
create or replace database and get connection........
Fatal error: Uncaught mysqli_sql_exception: Can't drop database 'tcexam'; database doesn't exist in C:\xampp\htdocs\tcexam\shared\code\tce_db_dal_mysqli.php:89 Stack trace: #0 C:\xampp\htdocs\tcexam\shared\code\tce_db_dal_mysqli.php(89): mysqli_query(Object(mysqli), 'DROP DATABASE t...') #1 C:\xampp\htdocs\tcexam\install\tce_functions_install.php(203): F_db_query('DROP DATABASE t...', Object(mysqli)) #2 C:\xampp\htdocs\tcexam\install\tce_functions_install.php(63): F_create_database('MYSQL', 'localhost', '3306', 'tcuser', '1234', 'tcexam', 'tce_', true, true) #3 C:\xampp\htdocs\tcexam\install\install.php(92): F_install_database('MYSQL', 'localhost', '3306', 'tcuser', '1234', 'tcexam', 'tce_', true, true, 'install.log') #4 {main} thrown in C:\xampp\htdocs\tcexam\shared\code\tce_db_dal_mysqli.php on line 89

**Comment by nicolaasuni** [comment]
v17 changed installation substantially (Composer-managed deps, rewritten installer, zero-touch Docker). Please retry with v17 following doc/INSTALL.md; if you still hit a fatal error, reopen with the exact message and your PHP version. Closing as stale against the old installer.
